function epsilon = OrthotropicStresses2Strains( sigma, Es, Gs )

% This function computes the strains, epsilon, generated by the given stresses, sigma, for an orthotropic material.

% Inputs:
    % sigma = 3 x 3 matrix of the form [sigma_xx tau_xy tau_xz; tau_yx sigma_yy tau_yz; tau_zx tau_zy sigma_zz]; that describes the stress state at the point of interest.
    % Es = 3 x 1 column vector of the form [E_x; E_y; E_z] orthotropic Young's (normal) modulii of elasticity.
    % Gs = 3 x 1 column vector of the form [G_x; G_y; G_z] orthotropic shear modulii of elasticity.

% Outputs:
    % epsilon = 3 x 3 matrix of the form [epsilon_xx gamma_xy gamma_xz; gamma_yx epsilon_yy gamma_yz; gamma_zx gamma_zy epsilon_zz]; that describes the strain state at the point of interest.

% Define the complimentary matrix.
C = [];

epsilon = [];

end

